# Render Blueprint for Flagright Fraud Detection System
# For manual deployment, see RENDER_MANUAL_DEPLOY.md

services:
  # Backend API Service
  - type: web
    name: flagright-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEO4J_URI
        value: "bolt://localhost:7687"
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        value: "password123"
    healthCheckPath: /health

  # Frontend Static Site  
  - type: web
    name: flagright-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    plan: free